services:
  build:
    environment:
      HOSTUID: ${HOSTUID}
      HOSTGID: ${HOSTGID}
      VERSION: "${VERSION:-1.0-10}"
      WORKSPACE: ${WORKSPACE}
    image: andy5995/linuxdeploy:v3-jammy
    volumes:
      - ${PWD}:${WORKSPACE}
    working_dir: ${WORKSPACE}
    # Absolute path or relative to workspace
    command: "${SCRIPT:-./make-appimage.sh}"
